/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Tutorial {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'thumbnailUrl' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'author' : string,
  'viewCount' : bigint,
  'category' : string,
  'rating' : number,
  'videoUrl' : string,
}
export interface _SERVICE {
  'getAllTutorials' : ActorMethod<[], Array<Tutorial>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getTrendingTutorials' : ActorMethod<[], Array<Tutorial>>,
  'getTutorialsByCategory' : ActorMethod<[string], Array<Tutorial>>,
  'incrementViewCount' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];