/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Tutorial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Text,
  'viewCount' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTrendingTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
  'getTutorialsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Tutorial)],
      ['query'],
    ),
  'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Tutorial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Text,
    'viewCount' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTrendingTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
    'getTutorialsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Tutorial)],
        ['query'],
      ),
    'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };